### ISSUE TITLE
Incorrect wav header errormessage

### ISSUE THREAD

**Issue by mtarenskeen** [joyrex2001/castools#3]
I am getting "Incorrect wav header" error message with wav2cas, compiled from git sources version 1.31.
But after I defined **unint32_t** as **unsigned int** instead of **unsigned long** in wav2cas.c, conversion of my wav files to cas files works fine now.

I don't know enough about this subject to tell if this is a bugfix or an ugly workaround.
I am using Linux Fedora 25, 64 bits, gcc 6.3.1

Just reporting.

**Comment by nataliapc** [comment]
You are right, it must be uint32_t, and others typedef from <stdint.h>, for compatibility with 64bits systems.

**Comment by joyrex2001** [comment]
Would it make sense to just add #include <stdint.h> to fix this?

**Comment by mtarenskeen** [comment]
On Wed, 1 Mar 2017, Vincent van Dam wrote:

> 
> Would it make sense to just add #include <stdint.h> to fix this?

Yes, it would. Unfortunately it still fails for me. I or it must still be 
missing something.

**Comment by joyrex2001** [comment]
I removed the typedefs, and replaced it for the stdint solution. I tested it with ubuntu-trusty-64 (and OSX) and that worked, I hope this works for you as well...
https://github.com/joyrex2001/castools/commit/2de25276b706d891fab1b51cfed1406ea74c4c52

**Comment by mtarenskeen** [comment]
On Mon, 6 Mar 2017, Vincent van Dam wrote:

> I removed the typedefs, and replaced it for the stdint solution. I tested it
> with ubuntu-trusty-64 (and OSX) and that worked, I hope this works for you
> as well...
> 2de2527

Yes, it also works on my Fedora 25 (64 bits) system. Thanks.

Maybe someone can try compiling and testing on 32 bits and Windows 
systems.

-- 

MT

**Comment by joyrex2001** [comment]
I have tested on an older 32-bit platform as well, and other than removing the "no-unused-result" warning option for newer gcc's, I had no issues. Thanks for your help guys!
